backend:
  name: github
  repo: facelessincomestudio/FIS
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }
          - { label: "Button Label", name: "hero_button", widget: "string" }

      - label: "About Page"
        name: "about"
        file: "content/pages/about.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "string" }
          - { label: "Main Text", name: "main_text", widget: "markdown" }

      - label: "Guides Page"
        name: "guides"
        file: "content/pages/guides.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Planners Page"
        name: "planners"
        file: "content/pages/planners.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Templates Page"
        name: "templates"
        file: "content/pages/templates.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Art Page"
        name: "art"
        file: "content/pages/art.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Freebies Page"
        name: "freebies"
        file: "content/pages/freebies.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Content Page"
        name: "content"
        file: "content/pages/content.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }

      - label: "Contact Page"
        name: "contact"
        file: "content/pages/contact.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "markdown" }
          - { label: "Email Address", name: "email", widget: "string" }

      - label: "Terms & Privacy Page"
        name: "terms"
        file: "content/pages/terms.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "string" }
          - { label: "Terms Body", name: "body", widget: "markdown" }
